steps:
  # 1. Frontend: Install & Lint
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--legacy-peer-deps', '--prefix', 'frontend']
    id: 'frontend-install'
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'lint', '--prefix', 'frontend']
    id: 'frontend-lint'
    waitFor: ['frontend-install']

  # 2. AI Engine: Test
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r ai-engine/requirements.txt
        pytest ai-engine/tests || echo "No tests found, skipping"
    id: 'ai-test'

  # 3. Build Docker Images (Parallel)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/app/frontend:$BUILD_ID', './frontend']
    id: 'build-frontend'
    waitFor: ['frontend-lint']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/app/backend:$BUILD_ID', './backend']
    id: 'build-backend'
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/app/ai-engine:$BUILD_ID', './ai-engine']
    id: 'build-ai'
    waitFor: ['ai-test']

  # 4. Push Images
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push us-central1-docker.pkg.dev/$PROJECT_ID/app/*:$BUILD_ID']
    waitFor: ['build-frontend', 'build-backend', 'build-ai']

# 5. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'codementor-frontend', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/app/frontend:$BUILD_ID', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
    id: 'deploy-frontend'
    
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'codementor-backend', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/app/backend:$BUILD_ID', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
    id: 'deploy-backend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'codementor-ai-engine', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/app/ai-engine:$BUILD_ID', '--region', 'us-central1', '--platform', 'managed', '--no-allow-unauthenticated'] # AI сервис лучше держать приватным
    id: 'deploy-ai'
timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
