steps:
  # 1. Frontend: Install & Lint
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--prefix', 'frontend']
    id: 'frontend-install'
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'lint', '--prefix', 'frontend']
    id: 'frontend-lint'
    waitFor: ['frontend-install']

  # 2. AI Engine: Test
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r ai-engine/requirements.txt
        pytest ai-engine/tests || echo "No tests found, skipping"
    id: 'ai-test'

  # 3. Build Docker Images (Parallel)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/app/frontend:$COMMIT_SHA', './frontend']
    id: 'build-frontend'
    waitFor: ['frontend-lint']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/app/backend:$COMMIT_SHA', './backend']
    id: 'build-backend'
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/app/ai-engine:$COMMIT_SHA', './ai-engine']
    id: 'build-ai'
    waitFor: ['ai-test']

  # 4. Push Images
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push us-central1-docker.pkg.dev/$PROJECT_ID/app/*:$COMMIT_SHA']
    waitFor: ['build-frontend', 'build-backend', 'build-ai']

  # 5. Preview Deploy (Conditional)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "Deploying Preview to Cloud Run..."
      # Add deploy logic here if needed or keep purely CI for now
timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
